{{- if .Values.archivematica_storage_service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "archivematica.fullname" . }}-storage-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archivematica.component.labels" (list . "storage-service") | nindent 4 }}
spec:
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    {{- include "archivematica.component.selectorLabels" (list . "storage-service") | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "archivematica.fullname" . }}-storage-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archivematica.component.labels" (list . "storage-service") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "archivematica.component.selectorLabels" (list . "storage-service") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "archivematica.component.selectorLabels" (list . "storage-service") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "archivematica.serviceAccountName" . }}
      securityContext:
        fsGroup: {{ .Values.general.user_uid }}
        runAsUser: {{ .Values.general.user_uid }}
        runAsGroup: {{ .Values.general.user_uid }}
      initContainers:
        - name: storage-service-migrations
          image: "{{ .Values.archivematica_storage_service.image.repository }}:{{ .Values.archivematica_storage_service.image.tag }}"
          imagePullPolicy: {{ .Values.archivematica_storage_service.image.pullPolicy }}
          securityContext:
            runAsUser: {{ .Values.general.user_uid }}
            runAsGroup: {{ .Values.general.user_uid }}
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          command: ["sh"]
          args: ["-c", "python /src/storage_service/manage.py migrate --noinput"]
          envFrom:
            - secretRef:
                name: {{ include "archivematica.fullname" . }}-secrets
          # envFrom:
          #   - configMapRef:
          #       name: {{ include "archivematica.fullname" . }}-env
          #   - secretRef:
          #       name: {{ include "archivematica.fullname" . }}-secrets
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "storage_service.settings.local" #"storage_service.settings.local"
            - name: SS_DB_URL
              value: {{ .Values.mysql.ss_db_url | quote }}
            - name: FORWARDED_ALLOW_IPS
              value: '*'
            - name: SS_GNUPG_HOME_PATH
              value: /var/archivematica/storage_service/.gnupg
            - name: SS_GUNICORN_ACCESSLOG
              value: /dev/null
            - name: SS_GUNICORN_RELOAD
              value: "true"
            - name: SS_GUNICORN_RELOAD_ENGINE
              value: auto
            - name: SS_DB_NAME
              value: "SS" # {{ .Values.mysql.db.name | quote }}
            - name: SS_DB_USER
              value: {{ .Values.mysql.db.user | quote }}
            - name: SS_DB_PASSWORD
              value: {{ .Values.mysql.db.password | quote }}
            - name: SS_DB_HOST
              value: {{ include "archivematica.fullname" . }}-mysql
            - name: SS_DB_PORT
              value: "3306"
        - name: archivematica-storage-service-create-user
          image: "{{ .Values.archivematica_storage_service.image.repository }}:{{ .Values.archivematica_storage_service.image.tag }}"
          imagePullPolicy: {{ .Values.archivematica_storage_service.image.pullPolicy }}
          securityContext:
            runAsUser: {{ .Values.general.user_uid }}
            runAsGroup: {{ .Values.general.user_uid }}
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          command: ["sh"]
          args: ["-c",'python /src/storage_service/manage.py create_user --username=$(AM_SS_USERNAME) --password=$(AM_SS_PASSWORD) --email=$(AM_SS_EMAIL) --api-key=$(AM_SS_API_KEY) --superuser ']
          envFrom:
            - secretRef:
                name: {{ include "archivematica.fullname" . }}-secrets
          # envFrom:
          #   - configMapRef:
          #       name: {{ include "archivematica.fullname" . }}-env
          #   - secretRef:
          #       name: {{ include "archivematica.fullname" . }}-secrets
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "storage_service.settings.local" #"storage_service.settings.local"
            - name: SS_DB_URL
              value: {{ .Values.mysql.ss_db_url | quote }}
            - name: FORWARDED_ALLOW_IPS
              value: '*'
            - name: SS_GNUPG_HOME_PATH
              value: /var/archivematica/storage_service/.gnupg
            - name: SS_GUNICORN_ACCESSLOG
              value: /dev/null
            - name: SS_GUNICORN_RELOAD
              value: "true"
            - name: SS_GUNICORN_RELOAD_ENGINE
              value: auto
            - name: SS_DB_NAME
              value: "SS" # {{ .Values.mysql.db.name | quote }}
            - name: SS_DB_USER
              value: {{ .Values.mysql.db.user | quote }}
            - name: SS_DB_PASSWORD
              value: {{ .Values.mysql.db.password | quote }}
            - name: SS_DB_HOST
              value: {{ include "archivematica.fullname" . }}-mysql
            - name: SS_DB_PORT
              value: "3306"
            - name: AM_SS_USERNAME
              valueFrom:
                secretKeyRef:
                  key: AM_SS_USERNAME
                  name: {{ include "archivematica.fullname" . }}-secrets
            - name: AM_SS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: AM_SS_PASSWORD
                  name: {{ include "archivematica.fullname" . }}-secrets
            - name: AM_SS_API_KEY
              valueFrom:
                secretKeyRef:
                  key: AM_SS_API_KEY
                  name: {{ include "archivematica.fullname" . }}-secrets
            - name: AM_SS_EMAIL
              valueFrom:
                secretKeyRef:
                  key: AM_SS_EMAIL
                  name: {{ include "archivematica.fullname" . }}-secrets
      containers:
        - name: storage-service
          image: "{{ .Values.archivematica_storage_service.image.repository }}:{{ .Values.archivematica_storage_service.image.tag }}"
          imagePullPolicy: {{ .Values.archivematica_storage_service.image.pullPolicy }}
          securityContext:
            runAsUser: {{ .Values.general.user_uid }}
            runAsGroup: {{ .Values.general.user_uid }}
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          ports:
            - containerPort: 8002
              name: http
          envFrom:
            - secretRef:
                name: {{ include "archivematica.fullname" . }}-secrets
          # envFrom:
          #   - configMapRef:
          #       name: {{ include "archivematica.fullname" . }}-env
          #   - secretRef:
          #       name: {{ include "archivematica.fullname" . }}-secrets
          env:
            # - name: DJANGO_SECRET_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: {{ include "archivematica.fullname" . }}-secrets
            #       key: DJANGO_SECRET_KEY
            - name: DJANGO_SETTINGS_MODULE
              value: "storage_service.settings.local" #"storage_service.settings.local"
            - name: SS_DB_URL
              value: {{ .Values.mysql.ss_db_url | quote }} # "mysql://$(SS_DB_USER):$(SS_DB_PASSWORD)@$(SS_DB_HOST):$(SS_DB_PORT)/$(SS_DB_NAME)"
            - name: FORWARDED_ALLOW_IPS
              value: '*'
            - name: SS_GNUPG_HOME_PATH
              value: /var/archivematica/storage_service/.gnupg
            - name: SS_GUNICORN_ACCESSLOG
              value: /dev/null
            - name: SS_GUNICORN_RELOAD
              value: "true"
            - name: SS_GUNICORN_RELOAD_ENGINE
              value: auto
            - name: SS_DB_NAME
              value: "SS" # {{ .Values.mysql.db.name | quote }}
            - name: SS_DB_USER
              value: {{ .Values.mysql.db.user | quote }}
            - name: SS_DB_PASSWORD
              value: {{ .Values.mysql.db.password | quote }}
            - name: SS_DB_HOST
              value: {{ include "archivematica.fullname" . }}-mysql
            - name: SS_DB_PORT
              value: "3306"
            - name: SS_GUNICORN_BIND
              value: "0.0.0.0:8002"
            - name: SS_GUNICORN_USER
              value: {{ .Values.general.user_uid | quote }}
            - name: SS_GUNICORN_GROUP
              value: {{ .Values.general.user_uid | quote }}
            # - name: SS_GUNICORN_LOGLEVEL
            #   value: "debug"
          volumeMounts:
            - name: pipeline-data
              mountPath: /var/archivematica/sharedDirectory
            - name: staging-data
              mountPath: /var/archivematica/storage_service
            - name: location-data
              mountPath: /home
              subPath: sips
            - name: transfer-share
              mountPath: /home/transfer
            - name: storage-share
              mountPath: /data/storage
          # Liveness and Readiness probes são recomendadas
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 1
      volumes:
        - name: pipeline-data
          persistentVolumeClaim:
            claimName: {{ include "archivematica.fullname" . }}-pipeline-data
        - name: staging-data
          persistentVolumeClaim:
            claimName: {{ include "archivematica.fullname" . }}-staging-data
        - name: location-data
          persistentVolumeClaim:
            claimName: {{ include "archivematica.fullname" . }}-location-data
        - name: transfer-share
          persistentVolumeClaim:
            claimName: {{ include "archivematica.fullname" . }}-transfer-share
        - name: storage-share
          persistentVolumeClaim:
            claimName: {{ include "archivematica.fullname" . }}-storage-share
{{- end }}