{{- if .Values.archivematica_storage_service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "archivematica.fullname" . }}-storage-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archivematica.component.labels" (list . "storage-service") | nindent 4 }}
spec:
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    {{- include "archivematica.component.selectorLabels" (list . "storage-service") | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "archivematica.fullname" . }}-storage-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archivematica.component.labels" (list . "storage-service") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "archivematica.component.selectorLabels" (list . "storage-service") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "archivematica.component.selectorLabels" (list . "storage-service") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "archivematica.serviceAccountName" . }}
      securityContext:
        fsGroup: {{ .Values.general.user_uid }}
        runAsUser: {{ .Values.general.user_uid }}
        runAsGroup: {{ .Values.general.user_uid }}
      initContainers:
        - name: storage-service-migrations
          image: "{{ .Values.archivematica_storage_service.image.repository }}:{{ .Values.archivematica_storage_service.image.tag }}"
          imagePullPolicy: {{ .Values.archivematica_storage_service.image.pullPolicy }}
          securityContext:
            runAsUser: {{ .Values.general.user_uid }}
            runAsGroup: {{ .Values.general.user_uid }}
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          command: ["sh"]
          args: ["-c", "python /src/storage_service/manage.py migrate --noinput"]
          envFrom:
            - configMapRef:
                name: {{ include "archivematica.fullname" . }}-env
            - secretRef:
                name: {{ include "archivematica.fullname" . }}-secrets
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "storage_service.settings.local"
            - name: SS_DB_URL
              value: {{ .Values.mysql.ss_db_url | quote }}
      containers:
        - name: storage-service
          image: "{{ .Values.archivematica_storage_service.image.repository }}:{{ .Values.archivematica_storage_service.image.tag }}"
          imagePullPolicy: {{ .Values.archivematica_storage_service.image.pullPolicy }}
          securityContext:
            runAsUser: {{ .Values.general.user_uid }}
            runAsGroup: {{ .Values.general.user_uid }}
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          ports:
            - containerPort: 8002
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "archivematica.fullname" . }}-env
            - secretRef:
                name: {{ include "archivematica.fullname" . }}-secrets
          env:
            - name: SS_GUNICORN_BIND
              value: "0.0.0.0:8002"
            - name: DJANGO_SETTINGS_MODULE
              value: "storage_service.settings.local"
            - name: SS_DB_URL
              value: {{ .Values.mysql.ss_db_url | quote }}
          volumeMounts:
            - name: pipeline-data
              mountPath: /var/archivematica/sharedDirectory
            - name: staging-data
              mountPath: /var/archivematica/storage_service
            - name: location-data
              mountPath: /home
              subPath: sips
            - name: transfer-share
              mountPath: /home/transfer
            - name: storage-share
              mountPath: /data/storage
          # Liveness and Readiness probes são recomendadas
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 1
      volumes:
        - name: pipeline-data
          persistentVolumeClaim:
            claimName: {{ include "archivematica.fullname" . }}-pipeline-data
        - name: staging-data
          persistentVolumeClaim:
            claimName: {{ include "archivematica.fullname" . }}-staging-data
        - name: location-data
          persistentVolumeClaim:
            claimName: {{ include "archivematica.fullname" . }}-location-data
        - name: transfer-share
          persistentVolumeClaim:
            claimName: {{ include "archivematica.fullname" . }}-transfer-share
        - name: storage-share
          persistentVolumeClaim:
            claimName: {{ include "archivematica.fullname" . }}-storage-share
{{- end }}