{{- if .Values.fits.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "archivematica.fullname" . }}-fits
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archivematica.component.labels" (list . "fits") | nindent 4 }}
spec:
  ports:
    - port: 2113
      targetPort: 2113
      protocol: TCP
      name: http
  selector:
    {{- include "archivematica.component.selectorLabels" (list . "fits") | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "archivematica.fullname" . }}-fits
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archivematica.component.labels" (list . "fits") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "archivematica.component.selectorLabels" (list . "fits") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "archivematica.component.selectorLabels" (list . "fits") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "archivematica.serviceAccountName" . }}
      securityContext:
        fsGroup: {{ .Values.general.user_uid }}
        runAsUser: {{ .Values.general.user_uid }}
        runAsGroup: {{ .Values.general.user_uid }}
      containers:
        - name: fits
          image: "{{ .Values.fits.image.repository }}:{{ .Values.fits.image.tag }}"
          imagePullPolicy: {{ .Values.fits.image.pullPolicy }}
          securityContext:
            runAsUser: {{ .Values.general.user_uid }}
            runAsGroup: {{ .Values.general.user_uid }}
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          ports:
            - containerPort: 2113
              name: http
          # Liveness and Readiness probes são recomendadas
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 1
          volumeMounts:
            - name: pipeline-data
              mountPath: /var/archivematica/sharedDirectory
      volumes:
        - name: pipeline-data
          persistentVolumeClaim:
            claimName: {{ include "archivematica.fullname" . }}-pipeline-data
{{- end }}