# Secret para senhas, chaves de API e outras informações sensíveis
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "archivematica.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archivematica.labels" . | nindent 4 }}
type: Opaque
data:
  # # Senhas do MySQL (codificadas em Base64)
  # MYSQL_USER: {{ .Values.mysql.db.user | b64enc | quote }}
  # MYSQL_ROOT_PASSWORD: {{ .Values.mysql.db.rootPassword | b64enc | quote }}
  # MYSQL_PASSWORD: {{ .Values.mysql.db.password | b64enc | quote }}
  # # SSDB_URL mysql://archivematica:archivematica@archivematica-mysql:3306/SS
  # SSDB_URL: {{ printf "mysql://%s:%s@%s-mysql:3306/SS" .Values.mysql.db.user .Values.mysql.db.password (include "archivematica.fullname" .) | b64enc | quote }}

  # Credenciais do usuário do Dashboard Archivematica (codificadas em Base64)
  # Estes valores devem ser gerados aleatoriamente ou fornecidos pelo usuário
  AM_DASHBOARD_USERNAME: {{ "JJpVwH2w1j"  | b64enc | quote }}
  AM_DASHBOARD_PASSWORD: {{ "RJz0M3audixEo29q" | b64enc | quote }}
  AM_DASHBOARD_API_KEY: {{ "3MOj9bbSVzJWF7etms5IAvcdxuhrCjjb" | b64enc | quote }}

  # Credenciais do usuário do Storage Service (codificadas em Base64)
  # Estes valores devem ser gerados aleatoriamente ou fornecidos pelo usuário
  AM_SS_USERNAME: {{ "jKmdYCBn1d" | b64enc | quote }}
  AM_SS_PASSWORD: {{ "lAWn8xPPdt9vVTEi" | b64enc | quote }}
  AM_SS_API_KEY: {{ "w3zT9jLp8vG7kY4nB1cR6sE2fH5aD0uV" | b64enc | quote }}
  AM_SS_EMAIL: {{ "daniel.carvalho@prodest.es.gov.br" | b64enc | quote }}
  # Chave secreta do Django (codificada em Base64)
  # Este valor deve ser gerado aleatoriamente
  DJANGO_SECRET_KEY: {{ "84211784" | b64enc | quote }}  # {{ randAlphaNum 50 | b64enc | quote }}

  # Adicione outras senhas ou chaves conforme necessário
---
# Secret para Mysql
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "archivematica.fullname" . }}-mysql-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archivematica.labels" . | nindent 4 }}
type: Opaque
data:
  # Senhas do MySQL (codificadas em Base64)
  MYSQL_USER: {{ .Values.mysql.db.user | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.db.rootPassword | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.db.password | b64enc | quote }}
  # SSDB_URL mysql://archivematica:archivematica@archivematica-mysql:3306/SS
  {{- if .Values.mysql.enabled }}
  SSDB_URL: {{ printf "mysql://%s:%s@%s-mysql:3306/SS" .Values.mysql.db.user .Values.mysql.db.password (include "archivematica.fullname" .) | b64enc | quote }}
  {{- end }}
