apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "archivematica.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archivematica.labels" . | nindent 4 }}
{{- if .Values.security.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.security.serviceAccount.annotations | nindent 4 }}
{{- end }}
