{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "archivematica.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archivematica.component.labels" (list . "redis") | nindent 4 }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "archivematica.component.selectorLabels" (list . "redis") | nindent 4 }}
  # clusterIP: None # Para StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "archivematica.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archivematica.component.labels" (list . "redis") | nindent 4 }}
spec:
  serviceName: {{ include "archivematica.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      {{- include "archivematica.component.selectorLabels" (list . "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "archivematica.component.selectorLabels" (list . "redis") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "archivematica.serviceAccountName" . }}
      securityContext:
        fsGroup: {{ .Values.general.user_uid }}
        runAsUser: {{ .Values.general.user_uid }}
        runAsGroup: {{ .Values.general.user_uid }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          securityContext:
            runAsUser: {{ .Values.general.user_uid }}
            runAsGroup: {{ .Values.general.user_uid }}
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          ports:
            - containerPort: 6379
              name: redis
          # Adicionar args ou configmap para configurar o Redis, se necessário
          # Exemplo: command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          volumeMounts:
            - name: redis-persistent-storage
              mountPath: /data
          # Liveness and Readiness probes são recomendadas
          # livenessProbe:
          #   tcpSocket:
          #     port: 6379
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 5
          # readinessProbe:
          #   exec:
          #     command:
          #     - redis-cli
          #     - ping
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 1
  volumeClaimTemplates:
    - metadata:
        name: redis-persistent-storage
      spec:
        accessModes: [ "{{ .Values.redis.persistence.accessMode }}" ]
        {{- if .Values.redis.persistence.storageClass }}
        storageClassName: "{{ .Values.redis.persistence.storageClass }}"
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size | quote }}
{{- end }}

